/**
 * Widget defaults — copy + chips per language. Mirrors the i18n table inside
 * the widget JS bundle so server-rendered fallbacks (and the /admin/widget
 * preview) read the same strings.
 *
 * Translations match the bundle's first-pass effort. Refine via the admin UI
 * by saving per-site copy overrides.
 *
 * ⚠ LEGACY VERTICAL SHAPE ⚠
 *
 * This widget's FIELD SCHEMA (pickup / dropoff / passengers / vehicle type)
 * belongs to the transport / chauffeur vertical that predated the current
 * cleaning-services focus. A cleaning-vertical booking form needs a
 * different shape (property type / area / room count / service type /
 * preferred date). Rather than half-rewrite the fields, this file has been
 * updated only to remove the most obviously transport-shaped copy (Toronto
 * / Pearson placeholders, "driver" taglines) — a fresh cleaning-vertical
 * widget should be authored separately when the operator wants embedded
 * booking on a Dubai cleaning site. Until then, per-site copy overrides
 * from the admin UI are the way to make this widget usable.
 */

export const DEFAULT_COPY = {
  en: {
    available_now: "AVAILABLE NOW",
    tagline: "Same-day quotes",
    headline: "Book in 30 seconds",
    subhead: "Speak it in plain English. We'll fill out the form for you.",
    placeholder: "e.g. 3-bedroom villa in Palm Jumeirah, deep clean on May 28 at 9am",
    try_one: "TRY ONE:",
    cta_continue: "Continue",
    cta_submit: "Get my quote",
    voice_booking: "Voice Booking",
    footer: "You may type or speak your request in plain English. We will complete the booking form for you.",
    fields: {
      pickup: "Pickup location",
      dropoff: "Drop-off location",
      datetime: "Pickup date & time",
      passengers: "Passengers",
      vehicle: "Vehicle type",
      notes: "Trip notes",
      name: "Your name",
      email: "Email",
      phone: "Phone",
    },
    success_title: "Quote received",
    success_body: "We'll text you a price within 5 minutes.",
    error_title: "Couldn't send",
    error_body: "Please try again or call us.",
  },
  fr: {
    available_now: "DISPONIBLE",
    tagline: "Devis le jour même",
    headline: "Réservez en 30 secondes",
    subhead: "Dites-le en français. Nous remplirons le formulaire pour vous.",
    placeholder: "ex. Villa 3 chambres à Palm Jumeirah, nettoyage en profondeur le 28 mai à 9h",
    try_one: "ESSAYEZ :",
    cta_continue: "Continuer",
    cta_submit: "Obtenir mon devis",
    voice_booking: "Réservation vocale",
    footer: "Tapez ou parlez votre demande en français. Nous remplirons le formulaire pour vous.",
    fields: {
      pickup: "Lieu de prise en charge",
      dropoff: "Lieu d'arrivée",
      datetime: "Date et heure",
      passengers: "Passagers",
      vehicle: "Type de véhicule",
      notes: "Notes",
      name: "Votre nom",
      email: "Courriel",
      phone: "Téléphone",
    },
    success_title: "Devis reçu",
    success_body: "Nous vous enverrons un prix par SMS dans les 5 minutes.",
    error_title: "Erreur d'envoi",
    error_body: "Veuillez réessayer ou nous appeler.",
  },
  pa: {
    available_now: "ਉਪਲਬਧ ਹੈ",
    tagline: "ਤੁਹਾਡਾ ਡਰਾਈਵਰ ਉਡੀਕ ਰਿਹਾ ਹੈ",
    headline: "30 ਸਕਿੰਟਾਂ ਵਿੱਚ ਬੁੱਕ ਕਰੋ",
    subhead: "ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲੋ। ਅਸੀਂ ਫਾਰਮ ਭਰ ਦੇਵਾਂਗੇ।",
    placeholder: "ਜਿਵੇਂ ਡਾਊਨਟਾਊਨ ਟੋਰਾਂਟੋ ਤੋਂ ਪੀਅਰਸਨ 28 ਮਈ ਨੂੰ 5 ਵਜੇ",
    try_one: "ਇਹ ਅਜ਼ਮਾਓ:",
    cta_continue: "ਅੱਗੇ ਵਧੋ",
    cta_submit: "ਮੇਰਾ ਕੋਟ ਲਓ",
    voice_booking: "ਆਵਾਜ਼ ਨਾਲ ਬੁੱਕਿੰਗ",
    footer: "ਆਪਣੀ ਬੇਨਤੀ ਪੰਜਾਬੀ ਵਿੱਚ ਟਾਈਪ ਕਰੋ ਜਾਂ ਬੋਲੋ।",
    fields: {
      pickup: "ਪਿਕਅੱਪ ਸਥਾਨ",
      dropoff: "ਡਰਾਪ-ਆਫ ਸਥਾਨ",
      datetime: "ਪਿਕਅੱਪ ਮਿਤੀ ਅਤੇ ਸਮਾਂ",
      passengers: "ਯਾਤਰੀ",
      vehicle: "ਵਾਹਨ ਦੀ ਕਿਸਮ",
      notes: "ਟਿੱਪਣੀਆਂ",
      name: "ਤੁਹਾਡਾ ਨਾਮ",
      email: "ਈਮੇਲ",
      phone: "ਫੋਨ",
    },
    success_title: "ਕੋਟ ਪ੍ਰਾਪਤ ਹੋਇਆ",
    success_body: "ਅਸੀਂ 5 ਮਿੰਟਾਂ ਵਿੱਚ ਤੁਹਾਨੂੰ ਕੀਮਤ ਭੇਜਾਂਗੇ।",
    error_title: "ਭੇਜਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ",
    error_body: "ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਸਾਨੂੰ ਕਾਲ ਕਰੋ।",
  },
  zh: {
    available_now: "现在可用",
    tagline: "您的司机正在等候",
    headline: "30秒内预订",
    subhead: "用中文说出您的需求，我们将为您填写表格。",
    placeholder: "例如：5月28日下午5点从多伦多市中心到皮尔逊机场，3人",
    try_one: "试试这个：",
    cta_continue: "继续",
    cta_submit: "获取报价",
    voice_booking: "语音预订",
    footer: "您可以用中文输入或说出您的请求。我们将为您完成预订表格。",
    fields: {
      pickup: "上车地点",
      dropoff: "下车地点",
      datetime: "上车日期和时间",
      passengers: "乘客人数",
      vehicle: "车辆类型",
      notes: "备注",
      name: "您的姓名",
      email: "电子邮件",
      phone: "电话",
    },
    success_title: "已收到报价",
    success_body: "我们将在5分钟内通过短信发送价格。",
    error_title: "发送失败",
    error_body: "请重试或致电我们。",
  },
  yue: {
    available_now: "現在可用",
    tagline: "當日報價",
    headline: "30秒內預訂",
    subhead: "用廣東話講你嘅需求，我哋會幫你填表。",
    placeholder: "例如：5月28日下午5點由多倫多市中心去皮爾遜機場，3個人",
    try_one: "試吓呢個：",
    cta_continue: "繼續",
    cta_submit: "獲取報價",
    voice_booking: "語音預訂",
    footer: "你可以用廣東話打字或者講你嘅請求。我哋會幫你填好預訂表。",
    fields: {
      pickup: "上車地點",
      dropoff: "落車地點",
      datetime: "上車日期同時間",
      passengers: "乘客人數",
      vehicle: "車輛類型",
      notes: "備註",
      name: "你嘅姓名",
      email: "電郵",
      phone: "電話",
    },
    success_title: "收到報價",
    success_body: "我哋會喺5分鐘內發短訊俾你個價錢。",
    error_title: "發送失敗",
    error_body: "請再試或者打電話俾我哋。",
  },
  ar: {
    available_now: "متاح الآن",
    tagline: "سائقك في انتظارك",
    headline: "احجز خلال 30 ثانية",
    subhead: "تحدث بالعربية وسنملأ النموذج نيابةً عنك.",
    placeholder: "مثال: من وسط تورنتو إلى مطار بيرسون في 28 مايو الساعة 5 مساءً",
    try_one: "جرّب هذا:",
    cta_continue: "متابعة",
    cta_submit: "احصل على عرض الأسعار",
    voice_booking: "الحجز الصوتي",
    footer: "اكتب أو تحدث بطلبك بالعربية. سنُكمل نموذج الحجز نيابةً عنك.",
    fields: {
      pickup: "موقع الاستلام",
      dropoff: "موقع التوصيل",
      datetime: "تاريخ ووقت الاستلام",
      passengers: "الركاب",
      vehicle: "نوع المركبة",
      notes: "ملاحظات الرحلة",
      name: "اسمك",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
    },
    success_title: "تم استلام الطلب",
    success_body: "سنُرسل لك السعر عبر الرسائل النصية خلال 5 دقائق.",
    error_title: "تعذّر الإرسال",
    error_body: "يُرجى المحاولة مرة أخرى أو الاتصال بنا.",
  },
  es: {
    available_now: "DISPONIBLE",
    tagline: "Tu chofer te espera",
    headline: "Reserva en 30 segundos",
    subhead: "Dilo en español. Llenaremos el formulario por ti.",
    placeholder: "ej. Villa 3 dormitorios en Palm Jumeirah, limpieza a fondo el 28 de mayo a las 9am",
    try_one: "PRUEBA:",
    cta_continue: "Continuar",
    cta_submit: "Obtener cotización",
    voice_booking: "Reserva por voz",
    footer: "Escribe o habla tu solicitud en español. Completaremos el formulario por ti.",
    fields: {
      pickup: "Lugar de recogida",
      dropoff: "Lugar de destino",
      datetime: "Fecha y hora",
      passengers: "Pasajeros",
      vehicle: "Tipo de vehículo",
      notes: "Notas",
      name: "Tu nombre",
      email: "Correo electrónico",
      phone: "Teléfono",
    },
    success_title: "Cotización recibida",
    success_body: "Te enviaremos el precio por SMS en 5 minutos.",
    error_title: "Error al enviar",
    error_body: "Por favor intenta de nuevo o llámanos.",
  },
  tl: {
    available_now: "MAY AVAILABLE",
    tagline: "Presyo sa parehong araw",
    headline: "Mag-book sa 30 segundo",
    subhead: "Sabihin sa Tagalog. Pupunan namin ang form para sa iyo.",
    placeholder: "hal. 3-kwartong villa sa Palm Jumeirah, malalim na paglilinis sa May 28 ng 9am",
    try_one: "SUBUKAN:",
    cta_continue: "Magpatuloy",
    cta_submit: "Kumuha ng quote",
    voice_booking: "Voice Booking",
    footer: "Maaari kang mag-type o magsalita ng request sa Tagalog. Aming kumpletuhin ang form para sa iyo.",
    fields: {
      pickup: "Pickup na lugar",
      dropoff: "Drop-off na lugar",
      datetime: "Petsa at oras",
      passengers: "Mga pasahero",
      vehicle: "Uri ng sasakyan",
      notes: "Mga tala",
      name: "Pangalan mo",
      email: "Email",
      phone: "Telepono",
    },
    success_title: "Natanggap ang quote",
    success_body: "Ipapadala namin sa iyo ang presyo sa text sa loob ng 5 minuto.",
    error_title: "Hindi naipadala",
    error_body: "Subukan ulit o tawagan kami.",
  },
  it: {
    available_now: "DISPONIBILE",
    tagline: "Preventivo in giornata",
    headline: "Prenota in 30 secondi",
    subhead: "Dillo in italiano. Compileremo il modulo per te.",
    placeholder: "es. Villa 3 camere a Palm Jumeirah, pulizia profonda il 28 maggio alle 9",
    try_one: "PROVA:",
    cta_continue: "Continua",
    cta_submit: "Ottieni preventivo",
    voice_booking: "Prenotazione vocale",
    footer: "Puoi digitare o parlare la tua richiesta in italiano. Completeremo il modulo per te.",
    fields: {
      pickup: "Luogo di partenza",
      dropoff: "Luogo di arrivo",
      datetime: "Data e ora",
      passengers: "Passeggeri",
      vehicle: "Tipo di veicolo",
      notes: "Note",
      name: "Il tuo nome",
      email: "Email",
      phone: "Telefono",
    },
    success_title: "Preventivo ricevuto",
    success_body: "Ti invieremo il prezzo via SMS entro 5 minuti.",
    error_title: "Invio non riuscito",
    error_body: "Riprova o chiamaci.",
  },
  pt: {
    available_now: "DISPONÍVEL",
    tagline: "Seu motorista aguarda",
    headline: "Reserve em 30 segundos",
    subhead: "Fale em português. Preencheremos o formulário para você.",
    placeholder: "ex. Villa de 3 quartos em Palm Jumeirah, limpeza profunda em 28 de maio às 9h",
    try_one: "EXPERIMENTE:",
    cta_continue: "Continuar",
    cta_submit: "Obter cotação",
    voice_booking: "Reserva por voz",
    footer: "Digite ou fale sua solicitação em português. Completaremos o formulário para você.",
    fields: {
      pickup: "Local de embarque",
      dropoff: "Local de desembarque",
      datetime: "Data e hora",
      passengers: "Passageiros",
      vehicle: "Tipo de veículo",
      notes: "Observações",
      name: "Seu nome",
      email: "E-mail",
      phone: "Telefone",
    },
    success_title: "Cotação recebida",
    success_body: "Enviaremos o preço por SMS em 5 minutos.",
    error_title: "Falha no envio",
    error_body: "Tente novamente ou ligue para nós.",
  },
} as const;

/**
 * Default suggestion chips. Legacy field names (`pickup` / `dropoff`) are
 * preserved for schema compatibility with the transport-vertical widget
 * bundle. For the cleaning-vertical use case the values below encode common
 * Dubai property + service pairs; per-site config can override these.
 */
export const DEFAULT_CHIPS = [
  { label: "Villa deep clean — Palm Jumeirah", pickup: "Palm Jumeirah villa", dropoff: "Deep clean" },
  { label: "Apartment maintenance — Dubai Marina", pickup: "Dubai Marina apartment", dropoff: "Standard clean" },
  { label: "Move-out clean — Downtown Dubai", pickup: "Downtown Dubai apartment", dropoff: "Move-out clean" },
  { label: "Sofa & carpet — Emirates Hills", pickup: "Emirates Hills villa", dropoff: "Sofa + carpet clean" },
] as const;
