import { createFileRoute } from "@tanstack/react-router";
import { useState, useEffect, useRef } from "react";
import { Bot, Send, Sparkles, Zap, Cpu, Loader2, AlertTriangle } from "lucide-react";
import { jobsStore } from "@/lib/jobs-store";
import { useSite } from "@/lib/site-context";
import { toast } from "sonner";

export const Route = createFileRoute("/assistant")({
  head: () => ({
    meta: [
      { title: "Assistant — AKS SEO Console" },
      { name: "description", content: "Chat with your AKS agent operator, backed by the real AKS worker queue." },
    ],
  }),
  component: AssistantPage,
});

type Msg = {
  role: "user" | "assistant";
  text: string;
  jobId?: string;
  jobStatus?: "pending" | "claimed" | "running" | "done" | "failed";
};

const POLL_MS = 3000;
const MAX_POLLS = 140; // ~7 minutes, matches every other real job poll in this app

/**
 * Polls the job's real claude_jobs row until it reaches a terminal state.
 * Same pattern as task-item-detail-modal.tsx's useJobStatus / suggestions.tsx's
 * pollOrchestratorJob -- this used to be three chained setTimeouts that faked
 * claim/heartbeat/complete against the real job row while actually generating
 * the "response" from a local keyword-matched string table. Now the response
 * is genuinely produced by the AKS worker running the claude CLI.
 */
async function pollJob(jobId: string, onStatus: (s: Msg["jobStatus"]) => void): Promise<{ status: string; text?: string }> {
  for (let i = 0; i < MAX_POLLS; i++) {
    await new Promise((r) => setTimeout(r, POLL_MS));
    const res = await fetch(`/api/jobs/${jobId}`);
    const json = await res.json().catch(() => null);
    const job = json?.job;
    if (!job) continue;
    if (job.status === "done") return { status: "done", text: job.outputMarkdown || "(empty response)" };
    if (job.status === "failed") return { status: "failed", text: job.error };
    onStatus(job.status);
  }
  return { status: "timeout" };
}

function formatMessageText(text: string) {
  const lines = text.split("\n");
  return lines.map((line, i) => {
    let content: React.ReactNode = line;

    // Bold parsing
    if (line.includes("**")) {
      const parts = line.split("**");
      content = parts.map((part, index) => index % 2 === 1 ? <strong key={index} className="font-bold text-white">{part}</strong> : part);
    }

    // Inline code parsing
    if (line.includes("`")) {
      const parts = line.split("`");
      content = parts.map((part, index) => index % 2 === 1 ? <code key={index} className="rounded bg-slate-900 px-1 py-0.5 font-mono text-cyan-300 text-xs border border-slate-800">{part}</code> : part);
    }

    if (line.startsWith("### ")) {
      return <h4 key={i} className="text-sm font-bold text-cyan-200 mt-3 mb-1.5 flex items-center gap-1.5">{line.slice(4)}</h4>;
    }
    if (line.startsWith("- ")) {
      return <li key={i} className="ml-4 list-disc text-xs text-slate-300 mt-1">{content}</li>;
    }
    return <p key={i} className="text-xs leading-relaxed text-slate-300 mt-1.5">{content}</p>;
  });
}

function AssistantPage() {
  const { currentSite } = useSite();
  const [msgs, setMsgs] = useState<Msg[]>([
    { role: "assistant", text: "Hi — ask me anything about your fleet, sites, or SEO ops. Your question is queued as a real job for the AKS worker; a `npm run worker` process needs to be running somewhere to answer it." },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [currentStatus, setCurrentStatus] = useState("");

  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [msgs, loading, currentStatus]);

  async function send() {
    if (!input.trim() || loading) return;

    const userPrompt = input;
    setInput("");
    setLoading(true);
    setCurrentStatus("Enqueuing in AKS Worker Queue…");

    const historyForPrompt = msgs.map((m) => ({ role: m.role, text: m.text }));
    setMsgs((m) => [...m, { role: "user", text: userPrompt }]);

    // Real job, real grounding: fetch the site's real structuredKb so
    // buildPromptForKind (job-templates.ts) can prepend real KB context --
    // no invented GA4/GSC numbers get generated by an LLM with no data.
    let structuredKb: unknown = undefined;
    if (currentSite?.id) {
      try {
        const siteRes = await fetch(`/api/sites/${currentSite.id}`);
        const siteJson = await siteRes.json();
        structuredKb = siteJson?.site?.structuredKb;
      } catch {
        /* proceed without KB grounding rather than blocking the chat */
      }
    }

    const job = await jobsStore.create({
      kind: "assistant:chat",
      title: `Leader Bot Chat: ${userPrompt.slice(0, 60)}`,
      input: {
        message: userPrompt,
        history: historyForPrompt,
        siteName: currentSite?.label,
        domain: currentSite?.domain,
        city: currentSite?.location,
        structuredKb,
      },
      priority: "high",
    });

    if (!job) {
      setLoading(false);
      setCurrentStatus("");
      toast.error("Failed to enqueue job");
      return;
    }

    setMsgs((m) => [...m, { role: "assistant", text: "", jobId: job.id, jobStatus: "pending" }]);
    setCurrentStatus("Waiting for the AKS worker — run `npm run worker` if none is running.");

    const result = await pollJob(job.id, (status) => {
      setMsgs((m) => m.map((msg) => (msg.jobId === job.id ? { ...msg, jobStatus: status } : msg)));
      setCurrentStatus(
        status === "running" ? "AKS worker is generating a response…"
        : status === "claimed" ? "Claimed by AKS worker…"
        : "Waiting for the AKS worker — run `npm run worker` if none is running.",
      );
    });

    if (result.status === "done") {
      setMsgs((m) => m.map((msg) => (msg.jobId === job.id ? { ...msg, text: result.text || "", jobStatus: "done" } : msg)));
    } else if (result.status === "failed") {
      setMsgs((m) => m.map((msg) => (msg.jobId === job.id ? { ...msg, text: `Job failed: ${result.text || "unknown error"}`, jobStatus: "failed" } : msg)));
      toast.error("AKS worker job failed");
    } else {
      setMsgs((m) => m.map((msg) => (msg.jobId === job.id ? { ...msg, text: "Still running in the background — check the Jobs Manager shortly." } : msg)));
      toast.info("Still running — this reply will appear once the worker finishes.");
    }

    setLoading(false);
    setCurrentStatus("");
  }

  return (
    <div className="min-h-screen bg-[#05070d] text-slate-200">
      <div className="mx-auto max-w-4xl px-6 py-8">
        <header className="mb-6 flex flex-wrap items-start justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-cyan-500/30 to-blue-600/30 ring-1 ring-cyan-400/40">
              <Bot className="h-5 w-5 text-cyan-200" />
            </div>
            <div>
              <h1 className="text-2xl font-semibold text-white">Fleet Chat Assistant</h1>
              <p className="text-xs text-slate-400">Real AKS worker queue (claude_jobs) — every reply is a genuine job, not a canned response.</p>
            </div>
          </div>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-400/30 bg-amber-400/10 px-2.5 py-1 text-[11px] font-medium text-amber-300">
            <AlertTriangle className="h-3 w-3" /> Requires a running worker
          </span>
        </header>

        <div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-5 shadow-xl">
          {/* Chat bubbles list */}
          <div className="scrollbar-thin mb-4 space-y-4 max-h-[50vh] min-h-[300px] overflow-y-auto pr-1">
            {msgs.map((m, i) => {
              const isUser = m.role === "user";
              const pending = !isUser && m.jobId && m.jobStatus !== "done" && m.jobStatus !== "failed";
              return (
                <div key={i} className={`flex flex-col ${isUser ? "items-end" : "items-start"}`}>
                  <div className={`max-w-[85%] rounded-2xl px-4 py-3 shadow-lg transition-all ${
                    isUser
                      ? "bg-cyan-500/10 border border-cyan-500/30 text-cyan-50"
                      : "bg-[#0b0f19] border border-slate-800 text-slate-200"
                  }`}>
                    {isUser ? (
                      <p className="text-xs">{m.text}</p>
                    ) : pending ? (
                      <div className="flex items-center gap-2 text-xs text-slate-400">
                        <Loader2 className="h-3.5 w-3.5 animate-spin text-cyan-300" /> {currentStatus || "Working…"}
                      </div>
                    ) : (
                      formatMessageText(m.text)
                    )}
                  </div>
                  {!isUser && m.jobId && (
                    <div className="mt-1 flex items-center gap-1.5 px-2 text-[10px] text-slate-500 font-mono">
                      <Cpu className="h-3 w-3 text-cyan-400" />
                      <span>Job: {m.jobId}</span>
                      {m.jobStatus && (
                        <>
                          <span>·</span>
                          <span className={m.jobStatus === "failed" ? "text-rose-400" : "text-emerald-400"}>{m.jobStatus}</span>
                        </>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
            <div ref={bottomRef} />
          </div>

          {/* Interactive Chat Input */}
          <div className="flex items-center gap-2 rounded-xl border border-slate-800 bg-slate-950/80 px-3.5 py-2.5 focus-within:border-cyan-400/40 transition">
            <Sparkles className="h-4 w-4 text-cyan-300 shrink-0" />
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && send()}
              disabled={loading}
              placeholder={loading ? "Worker is working…" : "Ask about analytics, position, alerts, cloudflare bots..."}
              className="flex-1 bg-transparent text-sm text-white placeholder:text-slate-500 outline-none disabled:opacity-50"
            />
            <button
              onClick={send}
              disabled={loading || !input.trim()}
              className="inline-flex items-center gap-1.5 rounded-lg bg-cyan-400 px-3.5 py-1.5 text-xs font-bold text-slate-950 hover:bg-cyan-300 transition disabled:opacity-50 cursor-pointer"
            >
              <Send className="h-3 w-3" /> Run
            </button>
          </div>
        </div>

        {/* Suggestion Prompts */}
        <div className="mt-6 grid gap-3 sm:grid-cols-4">
          {[
            { t: "Summarize this site's Knowledge Base", i: Zap },
            { t: "What SEO tasks are pending approval?", i: Sparkles },
            { t: "Explain the AKS agent fleet roles", i: Bot },
            { t: "What should I prioritize this week?", i: Cpu },
          ].map((q) => (
            <button
              key={q.t}
              onClick={() => setInput(q.t)}
              disabled={loading}
              className="rounded-xl border border-slate-800 bg-slate-950/40 p-3.5 text-left text-xs text-slate-400 hover:border-cyan-400/30 hover:text-white hover:bg-slate-950/70 transition duration-150 disabled:opacity-50 cursor-pointer"
            >
              <q.i className="mb-2 h-4 w-4 text-cyan-300" />
              <div className="font-semibold text-slate-200">{q.t}</div>
              <div className="mt-1 text-[10px] text-slate-500">Dispatch worker LLM</div>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
