import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { TaskItemDetailModal } from "@/features/tasks/components/task-item-detail-modal";
import type { Task } from "@/features/tasks/types";
import { useSite } from "@/lib/site-context";
import {
  Lightbulb,
  ArrowUpRight,
  Link2,
  FileText,
  Gauge,
  Braces,
  Compass,
  ListChecks,
  TrendingUp,
  Zap,
  Filter,
  Sparkles,
  Clock,
  Loader2,
} from "lucide-react";

export const Route = createFileRoute("/suggestions")({
  head: () => ({
    meta: [
      { title: "Suggestions — AKS SEO Console" },
      { name: "description", content: "Real SEO opportunities generated by the Head of SEO orchestrator, grouped by category." },
      { property: "og:title", content: "Suggestions — AKS SEO Console" },
      { property: "og:description", content: "Task recommendations grounded in live GSC/GA4 data and your Knowledge Base." },
    ],
  }),
  component: SuggestionsPage,
});

type Impact = "critical" | "high" | "medium" | "low";

// Matches the orchestrator's real category taxonomy (job-templates.ts's
// seo:orchestrator-review prompt, and Strategy Plan's producesTasks output)
// -- these are the actual values that land in kanban_tasks.templateId, not
// a fictional Off-Page/On-Page/Technical split invented for this page.
const CATEGORY_META: Record<string, { label: string; tagline: string; icon: typeof Link2; from: string; to: string }> = {
  technical: { label: "Technical SEO", tagline: "Crawl, schema, Core Web Vitals, indexation", icon: Gauge, from: "#818cf8", to: "#3b82f6" },
  content: { label: "Content & On-Page", tagline: "Pages, meta, headings, internal links", icon: FileText, from: "#34d399", to: "#14b8a6" },
  local: { label: "Local SEO", tagline: "GBP, NAP citations, area coverage", icon: Link2, from: "#fb923c", to: "#f97316" },
  schema: { label: "Structured Data", tagline: "JSON-LD, rich results eligibility", icon: Braces, from: "#38bdf8", to: "#6366f1" },
  strategy: { label: "Strategy & Authority", tagline: "PR, link building, roadmap items", icon: Compass, from: "#c084fc", to: "#e879f9" },
  other: { label: "Other", tagline: "Uncategorized recommendations", icon: Lightbulb, from: "#94a3b8", to: "#64748b" },
};

const CATEGORY_ORDER = ["technical", "content", "local", "schema", "strategy", "other"];

type SuggestionTask = {
  id: string;
  siteId: string | null;
  title: string;
  desc: string | null;
  assignee: string;
  priority: string;
  status: string;
  templateId: string | null;
  jobId: string | null;
  outputMarkdown: string | null;
  approvedBy: string | null;
  approvedAt: string | null;
  createdAt: string;
};

function priorityToImpact(priority: string): Impact {
  return ["critical", "high", "medium", "low"].includes(priority) ? (priority as Impact) : "medium";
}

async function pollOrchestratorJob(jobId: string, onStatus: (s: string) => void): Promise<string> {
  const POLL_MS = 3000;
  const MAX_ATTEMPTS = 140; // ~7 minutes, matches every other real job poll in this app
  for (let i = 0; i < MAX_ATTEMPTS; i++) {
    await new Promise((r) => setTimeout(r, POLL_MS));
    const res = await fetch(`/api/jobs/${jobId}`);
    const json = await res.json();
    const status = json?.job?.status;
    if (status === "done" || status === "failed") return status;
    if (status === "running") onStatus("AKS worker is analysing live data…");
    else if (status === "claimed") onStatus("AKS worker claimed the job…");
    else onStatus("Waiting for the AKS worker — run `npm run worker` if none is running.");
  }
  return "timeout";
}

function SuggestionsPage() {
  const { currentSite } = useSite();
  const [tasks, setTasks] = useState<SuggestionTask[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [genStatus, setGenStatus] = useState("");
  const [impactFilter, setImpactFilter] = useState<Impact | "all">("all");
  const [filterOpen, setFilterOpen] = useState(false);
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);

  const load = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/tasks");
      const json = await res.json();
      if (Array.isArray(json?.tasks)) {
        // Suggestions are recommendations, not the whole task board -- show
        // anything the orchestrator/Strategy Plan proposed regardless of
        // where it is in its lifecycle (pending_approval, todo, done, etc.)
        // but exclude ad-hoc manually-created tasks with no templateId,
        // since those aren't "suggestions" in any real sense.
        setTasks(json.tasks.filter((t: SuggestionTask) => !!t.templateId));
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const handleGenerate = async () => {
    if (generating || !currentSite.id) return;
    setGenerating(true);
    setGenStatus("Pulling live GSC + GA4 + Knowledge Base…");
    try {
      const res = await fetch("/api/orchestrator/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ siteId: currentSite.id }),
      });
      const json = await res.json();
      if (!json?.ok || !json.jobId) {
        toast.error(json?.error || "Failed to start suggestion generation");
        return;
      }
      setGenStatus("Waiting for the AKS worker — run `npm run worker` if none is running.");
      const status = await pollOrchestratorJob(json.jobId, setGenStatus);
      if (status === "done") {
        toast.success("New suggestions generated from live site data");
        await load();
      } else if (status === "failed") {
        toast.error("Suggestion generation failed. Check the worker logs.");
      } else {
        toast.info("Still running in the background — refresh shortly.");
      }
    } catch {
      toast.error("Failed to start suggestion generation");
    } finally {
      setGenerating(false);
      setGenStatus("");
    }
  };

  const [viewFilter, setViewFilter] = useState<"all" | "awaiting" | "highImpact" | "inMotion">("all");

  const filtered = useMemo(() => {
    let list = impactFilter === "all" ? tasks : tasks.filter((t) => priorityToImpact(t.priority) === impactFilter);
    if (viewFilter === "awaiting") list = list.filter((t) => t.status === "pending_approval");
    else if (viewFilter === "highImpact") list = list.filter((t) => t.priority === "critical" || t.priority === "high");
    else if (viewFilter === "inMotion") list = list.filter((t) => ["todo", "inprogress", "review"].includes(t.status));
    return list;
  }, [tasks, impactFilter, viewFilter]);

  const byCategory = useMemo(() => {
    const groups: Record<string, SuggestionTask[]> = {};
    for (const t of filtered) {
      const cat = t.templateId && CATEGORY_META[t.templateId] ? t.templateId : "other";
      (groups[cat] ||= []).push(t);
    }
    return groups;
  }, [filtered]);

  const total = tasks.length;
  const highImpact = tasks.filter((t) => t.priority === "critical" || t.priority === "high").length;
  const awaitingApproval = tasks.filter((t) => t.status === "pending_approval").length;
  const inMotion = tasks.filter((t) => ["todo", "inprogress", "review"].includes(t.status)).length;

  const openTaskModal = (t: SuggestionTask) => {
    setSelectedTask({
      id: t.id,
      title: t.title,
      desc: t.desc || undefined,
      assignee: t.assignee,
      priority: priorityToImpact(t.priority) as any,
      status: (t.status === "pending_approval" || t.status === "rejected" ? "todo" : t.status) as any,
      templateId: t.templateId || undefined,
      jobId: t.jobId || undefined,
      outputMarkdown: t.outputMarkdown || undefined,
      approvedBy: t.approvedBy,
      approvedAt: t.approvedAt,
      createdAt: t.createdAt,
    });
  };

  return (
    <div className="min-h-screen bg-[#05070d] text-slate-200">
      <div className="mx-auto max-w-[1600px] px-3 sm:px-4 py-10">
        {/* Header */}
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="text-[10px] font-medium uppercase tracking-[0.2em] text-cyan-300/80">
              Recommendations · Real, from your data
            </div>
            <h1 className="mt-1 text-2xl font-semibold text-white">Suggestions</h1>
            <p className="mt-1 text-sm text-slate-400">
              Every item here is a real task the Head of SEO orchestrator or Strategy Plan produced from{" "}
              {currentSite.label}'s live GSC/GA4 data and Knowledge Base — nothing on this page is invented.
              Tasks needing your sign-off go through <span className="text-cyan-300">/approvals</span> first.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <div className="relative">
              <button
                onClick={() => setFilterOpen((v) => !v)}
                className={`inline-flex items-center gap-2 rounded-md border px-3 py-1.5 text-xs font-medium transition ${
                  impactFilter !== "all" || filterOpen
                    ? "border-cyan-400/40 bg-cyan-400/10 text-cyan-100"
                    : "border-slate-700 bg-slate-900/60 text-slate-200 hover:bg-slate-800"
                }`}
              >
                <Filter className="h-4 w-4" /> Filter
                {impactFilter !== "all" && (
                  <span className="ml-1 rounded-full bg-cyan-400/25 px-1.5 text-[10px] font-semibold text-cyan-100">{impactFilter}</span>
                )}
              </button>
              {filterOpen && (
                <div className="absolute right-0 top-[calc(100%+6px)] z-30 w-52 overflow-hidden rounded-lg border border-slate-800 bg-slate-950/95 shadow-xl backdrop-blur">
                  <div className="border-b border-slate-800 px-3 py-2 text-[10px] uppercase tracking-wider text-slate-500">Priority</div>
                  {(["all", "critical", "high", "medium", "low"] as const).map((v) => (
                    <button
                      key={v}
                      onClick={() => {
                        setImpactFilter(v);
                        setFilterOpen(false);
                      }}
                      className={`flex w-full items-center justify-between px-3 py-2 text-left text-xs capitalize transition ${
                        impactFilter === v ? "bg-cyan-400/10 text-cyan-100" : "text-slate-300 hover:bg-slate-900"
                      }`}
                    >
                      <span>{v === "all" ? "All priorities" : `${v} priority`}</span>
                      {impactFilter === v && <span className="text-cyan-300">✓</span>}
                    </button>
                  ))}
                </div>
              )}
            </div>
            <button
              type="button"
              onClick={handleGenerate}
              disabled={generating || !currentSite.id}
              aria-busy={generating}
              className="inline-flex items-center gap-2 rounded-md border border-cyan-400/30 bg-cyan-400/10 px-3 py-1.5 text-sm font-medium text-cyan-200 transition hover:bg-cyan-400/20 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              {generating ? (genStatus || "Generating…") : "Generate new"}
            </button>
          </div>
        </div>

        {/* KPIs — click any card to filter the suggestions below to that view */}
        <section className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <KpiCard
            label="Total suggestions"
            value={total}
            sub="Across all categories"
            icon={ListChecks}
            from="#22d3ee"
            to="#0ea5e9"
            active={viewFilter === "all"}
            onClick={() => setViewFilter("all")}
          />
          <KpiCard
            label="Awaiting approval"
            value={awaitingApproval}
            sub="Sitting in /approvals"
            icon={Clock}
            from="#fbbf24"
            to="#f59e0b"
            active={viewFilter === "awaiting"}
            onClick={() => setViewFilter("awaiting")}
          />
          <KpiCard
            label="High / critical"
            value={highImpact}
            sub="Ship these first"
            icon={TrendingUp}
            from="#fb7185"
            to="#e11d48"
            active={viewFilter === "highImpact"}
            onClick={() => setViewFilter("highImpact")}
          />
          <KpiCard
            label="In motion"
            value={inMotion}
            sub="Approved, on the board"
            icon={Zap}
            from="#34d399"
            to="#14b8a6"
            active={viewFilter === "inMotion"}
            onClick={() => setViewFilter("inMotion")}
          />
        </section>
        {viewFilter !== "all" && (
          <div className="mt-2 flex items-center gap-2 text-[11px] text-slate-400">
            Showing: <span className="font-semibold text-cyan-300">
              {viewFilter === "awaiting" ? "Awaiting approval" : viewFilter === "highImpact" ? "High / critical" : "In motion"}
            </span>
            <button onClick={() => setViewFilter("all")} className="text-slate-500 underline hover:text-slate-300">
              Clear
            </button>
          </div>
        )}

        {/* Categories */}
        <div className="mt-8 space-y-6">
          {loading ? (
            <div className="rounded-2xl border border-dashed border-slate-800 bg-slate-900/30 p-10 text-center text-sm text-slate-500">
              Loading real suggestions…
            </div>
          ) : total === 0 ? (
            <div className="rounded-2xl border border-dashed border-slate-800 bg-slate-900/30 p-10 text-center text-sm text-slate-500">
              No suggestions yet for {currentSite.label}. Click "Generate new" to run the Head of SEO orchestrator
              against live GSC/GA4 data and your Knowledge Base.
            </div>
          ) : filtered.length === 0 ? (
            <div className="rounded-2xl border border-dashed border-slate-800 bg-slate-900/30 p-10 text-center text-sm text-slate-500">
              No suggestions match this filter.{" "}
              <button onClick={() => { setViewFilter("all"); setImpactFilter("all"); }} className="text-cyan-300 underline hover:text-cyan-200">
                Clear filters
              </button>
            </div>
          ) : (
            CATEGORY_ORDER.filter((cat) => byCategory[cat]?.length).map((cat) => (
              <CategorySection key={cat} categoryId={cat} tasks={byCategory[cat]} onOpen={openTaskModal} />
            ))
          )}
        </div>

        <div aria-hidden className="h-16" />
      </div>

      {selectedTask && (
        <TaskItemDetailModal
          task={selectedTask}
          onClose={() => setSelectedTask(null)}
          onUpdate={async (id, patch) => {
            await fetch(`/api/tasks/${id}`, {
              method: "PATCH",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(patch),
            });
            setSelectedTask(null);
            load();
          }}
          onDelete={async (id) => {
            await fetch(`/api/tasks/${id}`, { method: "DELETE" });
            setSelectedTask(null);
            load();
          }}
        />
      )}
    </div>
  );
}

function CategorySection({
  categoryId,
  tasks,
  onOpen,
}: {
  categoryId: string;
  tasks: SuggestionTask[];
  onOpen: (t: SuggestionTask) => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const meta = CATEGORY_META[categoryId] || CATEGORY_META.other;
  const Icon = meta.icon;
  const previewCount = 3;
  const items = expanded ? tasks : tasks.slice(0, previewCount);
  const remaining = tasks.length - previewCount;
  const highCount = tasks.filter((t) => t.priority === "critical" || t.priority === "high").length;

  return (
    <section className="relative overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/40">
      <div aria-hidden className="absolute inset-x-0 top-0 h-px" style={{ background: `linear-gradient(to right, ${meta.from}, ${meta.to})` }} />
      <div
        aria-hidden
        className="pointer-events-none absolute -right-16 -top-16 h-48 w-48 rounded-full opacity-[0.07] blur-3xl"
        style={{ background: `radial-gradient(circle, ${meta.from}, transparent 70%)` }}
      />

      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800/70 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="grid h-10 w-10 place-items-center rounded-xl text-slate-950 shadow" style={{ background: `linear-gradient(135deg, ${meta.from}, ${meta.to})` }}>
            <Icon className="h-4 w-4" />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-white">{meta.label}</h2>
            <div className="text-[11px] text-slate-500">{meta.tagline}</div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="rounded-full border border-slate-800 bg-slate-950/60 px-2 py-0.5 text-[10px] uppercase tracking-wider text-slate-400">
            {tasks.length} item{tasks.length === 1 ? "" : "s"}
          </span>
          {highCount > 0 && (
            <span
              className="rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider"
              style={{ color: meta.from, background: `color-mix(in oklab, ${meta.from} 12%, transparent)`, border: `1px solid color-mix(in oklab, ${meta.from} 25%, transparent)` }}
            >
              {highCount} high/critical
            </span>
          )}
        </div>
      </div>

      <ul className="divide-y divide-slate-800/70">
        {items.map((t) => (
          <SuggestionRow key={t.id} task={t} accentFrom={meta.from} accentTo={meta.to} onOpen={() => onOpen(t)} />
        ))}
      </ul>

      {tasks.length > previewCount && (
        <div className="flex items-center justify-between border-t border-slate-800/70 bg-slate-950/40 px-5 py-3">
          <div className="text-[11px] text-slate-500">Showing {items.length} of {tasks.length}</div>
          <button
            onClick={() => setExpanded((v) => !v)}
            className="inline-flex items-center gap-1.5 rounded-md border border-slate-700 bg-slate-900/60 px-3 py-1.5 text-xs font-medium text-slate-200 transition hover:border-cyan-400/40 hover:bg-slate-800 hover:text-cyan-200"
          >
            {expanded ? "Show less" : `View all (${remaining} more)`}
            <ArrowUpRight className="h-3.5 w-3.5" />
          </button>
        </div>
      )}
    </section>
  );
}

const STATUS_META: Record<string, string> = {
  pending_approval: "border-amber-400/25 bg-amber-500/10 text-amber-200",
  todo: "border-slate-700 bg-slate-800/50 text-slate-300",
  inprogress: "border-cyan-400/25 bg-cyan-500/10 text-cyan-200",
  review: "border-violet-400/25 bg-violet-500/10 text-violet-200",
  done: "border-emerald-400/25 bg-emerald-500/10 text-emerald-200",
  rejected: "border-rose-400/25 bg-rose-500/10 text-rose-300",
  resolved: "border-teal-400/25 bg-teal-500/10 text-teal-200",
};

const PRIORITY_META: Record<string, string> = {
  critical: "bg-rose-400/10 text-rose-200 border-rose-400/25",
  high: "bg-amber-400/10 text-amber-200 border-amber-400/25",
  medium: "bg-sky-400/10 text-sky-200 border-sky-400/25",
  low: "bg-slate-500/10 text-slate-400 border-slate-500/20",
};

function SuggestionRow({
  task,
  accentFrom,
  accentTo,
  onOpen,
}: {
  task: SuggestionTask;
  accentFrom: string;
  accentTo: string;
  onOpen: () => void;
}) {
  return (
    <li className="group relative flex items-start justify-between gap-4 px-5 py-4 transition hover:bg-slate-900/60">
      <div className="flex min-w-0 items-start gap-3 cursor-pointer" onClick={onOpen}>
        <div className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg text-slate-950" style={{ background: `linear-gradient(135deg, ${accentFrom}, ${accentTo})` }}>
          <Lightbulb className="h-3.5 w-3.5" />
        </div>
        <div className="min-w-0">
          <div className="text-sm font-medium text-white leading-snug group-hover:text-cyan-300 transition">{task.title}</div>
          {task.desc && <div className="mt-0.5 line-clamp-2 text-xs text-slate-400">{task.desc}</div>}
          <div className="mt-2 flex flex-wrap items-center gap-1.5">
            <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wider ${PRIORITY_META[task.priority] || PRIORITY_META.medium}`}>
              {task.priority}
            </span>
            <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wider ${STATUS_META[task.status] || STATUS_META.todo}`}>
              {task.status.replace("_", " ")}
            </span>
            <span className="inline-flex items-center gap-1 rounded-full border border-slate-800 bg-slate-950/60 px-2 py-0.5 text-[10px] uppercase tracking-wider text-slate-400">
              {task.assignee}
            </span>
          </div>
        </div>
      </div>
      <button
        type="button"
        onClick={onOpen}
        className="inline-flex shrink-0 items-center gap-1 rounded-md border border-cyan-400/30 bg-cyan-400/10 px-2.5 py-1 text-[11px] font-medium text-cyan-200 transition hover:bg-cyan-400/20"
      >
        Inspect <ArrowUpRight className="h-3 w-3" />
      </button>
    </li>
  );
}

function KpiCard({
  label,
  value,
  sub,
  icon: Icon,
  from,
  to,
  active,
  onClick,
}: {
  label: string;
  value: number;
  sub: string;
  icon: typeof Zap;
  from: string;
  to: string;
  active?: boolean;
  onClick?: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-pressed={active}
      className={`group relative overflow-hidden rounded-xl border p-4 text-left transition hover:-translate-y-0.5 ${
        active
          ? "border-cyan-400/50 bg-slate-900/80 shadow-[0_0_16px_rgba(34,211,238,0.15)]"
          : "border-slate-800 bg-slate-900/40 hover:border-slate-600 hover:bg-slate-900/70"
      }`}
    >
      <div
        aria-hidden
        className="absolute -right-8 -top-8 h-24 w-24 rounded-full opacity-10 blur-2xl transition-opacity group-hover:opacity-20"
        style={{ background: `radial-gradient(circle, ${from}, transparent 70%)` }}
      />
      {active && (
        <div aria-hidden className="absolute inset-x-0 top-0 h-0.5" style={{ background: `linear-gradient(to right, ${from}, ${to})` }} />
      )}
      <div className="flex items-center gap-1.5 text-[11px] uppercase tracking-wider text-slate-500">
        <Icon className="h-3 w-3" style={{ color: from }} /> {label}
      </div>
      <div className="mt-1.5 text-2xl font-semibold tracking-tight text-white tabular-nums">{value}</div>
      <div className="mt-0.5 text-[10px] text-slate-500">{sub}</div>
    </button>
  );
}
