/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AnalyticsSearchConsoleRouteImport } from './routes/analytics.search-console'
import { Route as AnalyticsGoogleAnalyticsRouteImport } from './routes/analytics.google-analytics'
import { Route as AnalyticsBusinessProfileRouteImport } from './routes/analytics.business-profile'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'

const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsSearchConsoleRoute = AnalyticsSearchConsoleRouteImport.update({
  id: '/analytics/search-console',
  path: '/analytics/search-console',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsGoogleAnalyticsRoute =
  AnalyticsGoogleAnalyticsRouteImport.update({
    id: '/analytics/google-analytics',
    path: '/analytics/google-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnalyticsBusinessProfileRoute =
  AnalyticsBusinessProfileRouteImport.update({
    id: '/analytics/business-profile',
    path: '/analytics/business-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/analytics/': typeof AnalyticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/analytics': typeof AnalyticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/analytics/': typeof AnalyticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/automation'
    | '/dashboard'
    | '/settings'
    | '/suggestions'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/analytics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/automation'
    | '/dashboard'
    | '/settings'
    | '/suggestions'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/analytics'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/automation'
    | '/dashboard'
    | '/settings'
    | '/suggestions'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/analytics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AutomationRoute: typeof AutomationRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  SuggestionsRoute: typeof SuggestionsRoute
  AgentsIdRoute: typeof AgentsIdRoute
  AnalyticsBusinessProfileRoute: typeof AnalyticsBusinessProfileRoute
  AnalyticsGoogleAnalyticsRoute: typeof AnalyticsGoogleAnalyticsRoute
  AnalyticsSearchConsoleRoute: typeof AnalyticsSearchConsoleRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/search-console': {
      id: '/analytics/search-console'
      path: '/analytics/search-console'
      fullPath: '/analytics/search-console'
      preLoaderRoute: typeof AnalyticsSearchConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/google-analytics': {
      id: '/analytics/google-analytics'
      path: '/analytics/google-analytics'
      fullPath: '/analytics/google-analytics'
      preLoaderRoute: typeof AnalyticsGoogleAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/business-profile': {
      id: '/analytics/business-profile'
      path: '/analytics/business-profile'
      fullPath: '/analytics/business-profile'
      preLoaderRoute: typeof AnalyticsBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AutomationRoute: AutomationRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  SuggestionsRoute: SuggestionsRoute,
  AgentsIdRoute: AgentsIdRoute,
  AnalyticsBusinessProfileRoute: AnalyticsBusinessProfileRoute,
  AnalyticsGoogleAnalyticsRoute: AnalyticsGoogleAnalyticsRoute,
  AnalyticsSearchConsoleRoute: AnalyticsSearchConsoleRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
