/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgencyHealthRouteImport } from './routes/agency-health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeoSuiteIndexRouteImport } from './routes/seo-suite.index'
import { Route as ScoutTeamIndexRouteImport } from './routes/scout-team.index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as SeoSuiteToolIdRouteImport } from './routes/seo-suite.$toolId'
import { Route as ScoutTeamScoutIdRouteImport } from './routes/scout-team.$scoutId'
import { Route as AnalyticsSearchConsoleRouteImport } from './routes/analytics.search-console'
import { Route as AnalyticsGoogleAnalyticsRouteImport } from './routes/analytics.google-analytics'
import { Route as AnalyticsBusinessProfileRouteImport } from './routes/analytics.business-profile'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyHealthRoute = AgencyHealthRouteImport.update({
  id: '/agency-health',
  path: '/agency-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSuiteIndexRoute = SeoSuiteIndexRouteImport.update({
  id: '/seo-suite/',
  path: '/seo-suite/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutTeamIndexRoute = ScoutTeamIndexRouteImport.update({
  id: '/scout-team/',
  path: '/scout-team/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSuiteToolIdRoute = SeoSuiteToolIdRouteImport.update({
  id: '/seo-suite/$toolId',
  path: '/seo-suite/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutTeamScoutIdRoute = ScoutTeamScoutIdRouteImport.update({
  id: '/scout-team/$scoutId',
  path: '/scout-team/$scoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsSearchConsoleRoute = AnalyticsSearchConsoleRouteImport.update({
  id: '/analytics/search-console',
  path: '/analytics/search-console',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsGoogleAnalyticsRoute =
  AnalyticsGoogleAnalyticsRouteImport.update({
    id: '/analytics/google-analytics',
    path: '/analytics/google-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnalyticsBusinessProfileRoute =
  AnalyticsBusinessProfileRouteImport.update({
    id: '/analytics/business-profile',
    path: '/analytics/business-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency-health': typeof AgencyHealthRoute
  '/alerts': typeof AlertsRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/team': typeof TeamRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/scout-team/$scoutId': typeof ScoutTeamScoutIdRoute
  '/seo-suite/$toolId': typeof SeoSuiteToolIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/scout-team/': typeof ScoutTeamIndexRoute
  '/seo-suite/': typeof SeoSuiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency-health': typeof AgencyHealthRoute
  '/alerts': typeof AlertsRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/team': typeof TeamRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/scout-team/$scoutId': typeof ScoutTeamScoutIdRoute
  '/seo-suite/$toolId': typeof SeoSuiteToolIdRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/scout-team': typeof ScoutTeamIndexRoute
  '/seo-suite': typeof SeoSuiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency-health': typeof AgencyHealthRoute
  '/alerts': typeof AlertsRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/team': typeof TeamRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/scout-team/$scoutId': typeof ScoutTeamScoutIdRoute
  '/seo-suite/$toolId': typeof SeoSuiteToolIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/scout-team/': typeof ScoutTeamIndexRoute
  '/seo-suite/': typeof SeoSuiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency-health'
    | '/alerts'
    | '/automation'
    | '/dashboard'
    | '/settings'
    | '/suggestions'
    | '/team'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/scout-team/$scoutId'
    | '/seo-suite/$toolId'
    | '/analytics/'
    | '/scout-team/'
    | '/seo-suite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency-health'
    | '/alerts'
    | '/automation'
    | '/dashboard'
    | '/settings'
    | '/suggestions'
    | '/team'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/scout-team/$scoutId'
    | '/seo-suite/$toolId'
    | '/analytics'
    | '/scout-team'
    | '/seo-suite'
  id:
    | '__root__'
    | '/'
    | '/agency-health'
    | '/alerts'
    | '/automation'
    | '/dashboard'
    | '/settings'
    | '/suggestions'
    | '/team'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/scout-team/$scoutId'
    | '/seo-suite/$toolId'
    | '/analytics/'
    | '/scout-team/'
    | '/seo-suite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyHealthRoute: typeof AgencyHealthRoute
  AlertsRoute: typeof AlertsRoute
  AutomationRoute: typeof AutomationRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  SuggestionsRoute: typeof SuggestionsRoute
  TeamRoute: typeof TeamRoute
  AgentsIdRoute: typeof AgentsIdRoute
  AnalyticsBusinessProfileRoute: typeof AnalyticsBusinessProfileRoute
  AnalyticsGoogleAnalyticsRoute: typeof AnalyticsGoogleAnalyticsRoute
  AnalyticsSearchConsoleRoute: typeof AnalyticsSearchConsoleRoute
  ScoutTeamScoutIdRoute: typeof ScoutTeamScoutIdRoute
  SeoSuiteToolIdRoute: typeof SeoSuiteToolIdRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  ScoutTeamIndexRoute: typeof ScoutTeamIndexRoute
  SeoSuiteIndexRoute: typeof SeoSuiteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-health': {
      id: '/agency-health'
      path: '/agency-health'
      fullPath: '/agency-health'
      preLoaderRoute: typeof AgencyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-suite/': {
      id: '/seo-suite/'
      path: '/seo-suite'
      fullPath: '/seo-suite/'
      preLoaderRoute: typeof SeoSuiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout-team/': {
      id: '/scout-team/'
      path: '/scout-team'
      fullPath: '/scout-team/'
      preLoaderRoute: typeof ScoutTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-suite/$toolId': {
      id: '/seo-suite/$toolId'
      path: '/seo-suite/$toolId'
      fullPath: '/seo-suite/$toolId'
      preLoaderRoute: typeof SeoSuiteToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout-team/$scoutId': {
      id: '/scout-team/$scoutId'
      path: '/scout-team/$scoutId'
      fullPath: '/scout-team/$scoutId'
      preLoaderRoute: typeof ScoutTeamScoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/search-console': {
      id: '/analytics/search-console'
      path: '/analytics/search-console'
      fullPath: '/analytics/search-console'
      preLoaderRoute: typeof AnalyticsSearchConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/google-analytics': {
      id: '/analytics/google-analytics'
      path: '/analytics/google-analytics'
      fullPath: '/analytics/google-analytics'
      preLoaderRoute: typeof AnalyticsGoogleAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/business-profile': {
      id: '/analytics/business-profile'
      path: '/analytics/business-profile'
      fullPath: '/analytics/business-profile'
      preLoaderRoute: typeof AnalyticsBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyHealthRoute: AgencyHealthRoute,
  AlertsRoute: AlertsRoute,
  AutomationRoute: AutomationRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  SuggestionsRoute: SuggestionsRoute,
  TeamRoute: TeamRoute,
  AgentsIdRoute: AgentsIdRoute,
  AnalyticsBusinessProfileRoute: AnalyticsBusinessProfileRoute,
  AnalyticsGoogleAnalyticsRoute: AnalyticsGoogleAnalyticsRoute,
  AnalyticsSearchConsoleRoute: AnalyticsSearchConsoleRoute,
  ScoutTeamScoutIdRoute: ScoutTeamScoutIdRoute,
  SeoSuiteToolIdRoute: SeoSuiteToolIdRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  ScoutTeamIndexRoute: ScoutTeamIndexRoute,
  SeoSuiteIndexRoute: SeoSuiteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
