/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencyHealthRouteImport } from './routes/agency-health'
import { Route as AgentDashboardRouteImport } from './routes/agent-dashboard'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AssignTasksRouteImport } from './routes/assign-tasks'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as BuildAgentRouteImport } from './routes/build-agent'
import { Route as ConnectedSitesRouteImport } from './routes/connected-sites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as QaSuiteRouteImport } from './routes/qa-suite'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AnalyticsBusinessProfileRouteImport } from './routes/analytics.business-profile'
import { Route as AnalyticsGoogleAnalyticsRouteImport } from './routes/analytics.google-analytics'
import { Route as AnalyticsSearchConsoleRouteImport } from './routes/analytics.search-console'
import { Route as ResourcesPromptsRouteImport } from './routes/resources.prompts'
import { Route as ResourcesSopsRouteImport } from './routes/resources.sops'
import { Route as ResourcesTemplatesRouteImport } from './routes/resources.templates'
import { Route as ScoutTeamIndexRouteImport } from './routes/scout-team.index'
import { Route as ScoutTeamScoutIdRouteImport } from './routes/scout-team.$scoutId'
import { Route as SeoSuiteIndexRouteImport } from './routes/seo-suite.index'
import { Route as SeoSuiteToolIdRouteImport } from './routes/seo-suite.$toolId'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as ApiAnalyticsSyncRouteImport } from './routes/api.analytics.sync'
import { Route as ApiAutomationFlowsRouteImport } from './routes/api.automation.flows'
import { Route as ApiEventsIngestRouteImport } from './routes/api.events.ingest'
import { Route as ApiGoogleGa4RouteImport } from './routes/api.google.ga4'
import { Route as ApiGoogleGbpRouteImport } from './routes/api.google.gbp'
import { Route as ApiGoogleSearchConsoleRouteImport } from './routes/api.google.search-console'
import { Route as ApiJobsIndexRouteImport } from './routes/api.jobs.index'
import { Route as ApiJobsClaimRouteImport } from './routes/api.jobs.claim'
import { Route as ApiTasksIndexRouteImport } from './routes/api.tasks.index'
import { Route as ApiTasksIdRouteImport } from './routes/api.tasks.$id'
import { Route as ApiAutomationFlowsIdRouteImport } from './routes/api.automation.flows.$id'
import { Route as ApiJobsIdCompleteRouteImport } from './routes/api.jobs.$id.complete'
import { Route as ApiJobsIdFailRouteImport } from './routes/api.jobs.$id.fail'
import { Route as ApiJobsIdHeartbeatRouteImport } from './routes/api.jobs.$id.heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyHealthRoute = AgencyHealthRouteImport.update({
  id: '/agency-health',
  path: '/agency-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent-dashboard',
  path: '/agent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignTasksRoute = AssignTasksRouteImport.update({
  id: '/assign-tasks',
  path: '/assign-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildAgentRoute = BuildAgentRouteImport.update({
  id: '/build-agent',
  path: '/build-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedSitesRoute = ConnectedSitesRouteImport.update({
  id: '/connected-sites',
  path: '/connected-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const QaSuiteRoute = QaSuiteRouteImport.update({
  id: '/qa-suite',
  path: '/qa-suite',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsBusinessProfileRoute =
  AnalyticsBusinessProfileRouteImport.update({
    id: '/analytics/business-profile',
    path: '/analytics/business-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnalyticsGoogleAnalyticsRoute =
  AnalyticsGoogleAnalyticsRouteImport.update({
    id: '/analytics/google-analytics',
    path: '/analytics/google-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnalyticsSearchConsoleRoute = AnalyticsSearchConsoleRouteImport.update({
  id: '/analytics/search-console',
  path: '/analytics/search-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesPromptsRoute = ResourcesPromptsRouteImport.update({
  id: '/resources/prompts',
  path: '/resources/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSopsRoute = ResourcesSopsRouteImport.update({
  id: '/resources/sops',
  path: '/resources/sops',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesTemplatesRoute = ResourcesTemplatesRouteImport.update({
  id: '/resources/templates',
  path: '/resources/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutTeamIndexRoute = ScoutTeamIndexRouteImport.update({
  id: '/scout-team/',
  path: '/scout-team/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutTeamScoutIdRoute = ScoutTeamScoutIdRouteImport.update({
  id: '/scout-team/$scoutId',
  path: '/scout-team/$scoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSuiteIndexRoute = SeoSuiteIndexRouteImport.update({
  id: '/seo-suite/',
  path: '/seo-suite/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSuiteToolIdRoute = SeoSuiteToolIdRouteImport.update({
  id: '/seo-suite/$toolId',
  path: '/seo-suite/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsSyncRoute = ApiAnalyticsSyncRouteImport.update({
  id: '/api/analytics/sync',
  path: '/api/analytics/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationFlowsRoute = ApiAutomationFlowsRouteImport.update({
  id: '/api/automation/flows',
  path: '/api/automation/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIngestRoute = ApiEventsIngestRouteImport.update({
  id: '/api/events/ingest',
  path: '/api/events/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleGa4Route = ApiGoogleGa4RouteImport.update({
  id: '/api/google/ga4',
  path: '/api/google/ga4',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleGbpRoute = ApiGoogleGbpRouteImport.update({
  id: '/api/google/gbp',
  path: '/api/google/gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleSearchConsoleRoute = ApiGoogleSearchConsoleRouteImport.update({
  id: '/api/google/search-console',
  path: '/api/google/search-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsClaimRoute = ApiJobsClaimRouteImport.update({
  id: '/api/jobs/claim',
  path: '/api/jobs/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIndexRoute = ApiTasksIndexRouteImport.update({
  id: '/api/tasks/',
  path: '/api/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/api/tasks/$id',
  path: '/api/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutomationFlowsIdRoute = ApiAutomationFlowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAutomationFlowsRoute,
} as any)
const ApiJobsIdCompleteRoute = ApiJobsIdCompleteRouteImport.update({
  id: '/api/jobs/$id/complete',
  path: '/api/jobs/$id/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdFailRoute = ApiJobsIdFailRouteImport.update({
  id: '/api/jobs/$id/fail',
  path: '/api/jobs/$id/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdHeartbeatRoute = ApiJobsIdHeartbeatRouteImport.update({
  id: '/api/jobs/$id/heartbeat',
  path: '/api/jobs/$id/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency-health': typeof AgencyHealthRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/alerts': typeof AlertsRoute
  '/assign-tasks': typeof AssignTasksRoute
  '/assistant': typeof AssistantRoute
  '/automation': typeof AutomationRoute
  '/build-agent': typeof BuildAgentRoute
  '/connected-sites': typeof ConnectedSitesRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/qa-suite': typeof QaSuiteRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/resources/prompts': typeof ResourcesPromptsRoute
  '/resources/sops': typeof ResourcesSopsRoute
  '/resources/templates': typeof ResourcesTemplatesRoute
  '/scout-team/$scoutId': typeof ScoutTeamScoutIdRoute
  '/seo-suite/$toolId': typeof SeoSuiteToolIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/scout-team/': typeof ScoutTeamIndexRoute
  '/seo-suite/': typeof SeoSuiteIndexRoute
  '/api/analytics/sync': typeof ApiAnalyticsSyncRoute
  '/api/automation/flows': typeof ApiAutomationFlowsRouteWithChildren
  '/api/events/ingest': typeof ApiEventsIngestRoute
  '/api/google/ga4': typeof ApiGoogleGa4Route
  '/api/google/gbp': typeof ApiGoogleGbpRoute
  '/api/google/search-console': typeof ApiGoogleSearchConsoleRoute
  '/api/jobs/claim': typeof ApiJobsClaimRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/automation/flows/$id': typeof ApiAutomationFlowsIdRoute
  '/api/jobs/$id/complete': typeof ApiJobsIdCompleteRoute
  '/api/jobs/$id/fail': typeof ApiJobsIdFailRoute
  '/api/jobs/$id/heartbeat': typeof ApiJobsIdHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency-health': typeof AgencyHealthRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/alerts': typeof AlertsRoute
  '/assign-tasks': typeof AssignTasksRoute
  '/assistant': typeof AssistantRoute
  '/automation': typeof AutomationRoute
  '/build-agent': typeof BuildAgentRoute
  '/connected-sites': typeof ConnectedSitesRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/qa-suite': typeof QaSuiteRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/resources/prompts': typeof ResourcesPromptsRoute
  '/resources/sops': typeof ResourcesSopsRoute
  '/resources/templates': typeof ResourcesTemplatesRoute
  '/scout-team/$scoutId': typeof ScoutTeamScoutIdRoute
  '/seo-suite/$toolId': typeof SeoSuiteToolIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/agents': typeof AgentsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/scout-team': typeof ScoutTeamIndexRoute
  '/seo-suite': typeof SeoSuiteIndexRoute
  '/api/analytics/sync': typeof ApiAnalyticsSyncRoute
  '/api/automation/flows': typeof ApiAutomationFlowsRouteWithChildren
  '/api/events/ingest': typeof ApiEventsIngestRoute
  '/api/google/ga4': typeof ApiGoogleGa4Route
  '/api/google/gbp': typeof ApiGoogleGbpRoute
  '/api/google/search-console': typeof ApiGoogleSearchConsoleRoute
  '/api/jobs/claim': typeof ApiJobsClaimRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/tasks': typeof ApiTasksIndexRoute
  '/api/automation/flows/$id': typeof ApiAutomationFlowsIdRoute
  '/api/jobs/$id/complete': typeof ApiJobsIdCompleteRoute
  '/api/jobs/$id/fail': typeof ApiJobsIdFailRoute
  '/api/jobs/$id/heartbeat': typeof ApiJobsIdHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency-health': typeof AgencyHealthRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/alerts': typeof AlertsRoute
  '/assign-tasks': typeof AssignTasksRoute
  '/assistant': typeof AssistantRoute
  '/automation': typeof AutomationRoute
  '/build-agent': typeof BuildAgentRoute
  '/connected-sites': typeof ConnectedSitesRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/qa-suite': typeof QaSuiteRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/analytics/business-profile': typeof AnalyticsBusinessProfileRoute
  '/analytics/google-analytics': typeof AnalyticsGoogleAnalyticsRoute
  '/analytics/search-console': typeof AnalyticsSearchConsoleRoute
  '/resources/prompts': typeof ResourcesPromptsRoute
  '/resources/sops': typeof ResourcesSopsRoute
  '/resources/templates': typeof ResourcesTemplatesRoute
  '/scout-team/$scoutId': typeof ScoutTeamScoutIdRoute
  '/seo-suite/$toolId': typeof SeoSuiteToolIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/scout-team/': typeof ScoutTeamIndexRoute
  '/seo-suite/': typeof SeoSuiteIndexRoute
  '/api/analytics/sync': typeof ApiAnalyticsSyncRoute
  '/api/automation/flows': typeof ApiAutomationFlowsRouteWithChildren
  '/api/events/ingest': typeof ApiEventsIngestRoute
  '/api/google/ga4': typeof ApiGoogleGa4Route
  '/api/google/gbp': typeof ApiGoogleGbpRoute
  '/api/google/search-console': typeof ApiGoogleSearchConsoleRoute
  '/api/jobs/claim': typeof ApiJobsClaimRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/automation/flows/$id': typeof ApiAutomationFlowsIdRoute
  '/api/jobs/$id/complete': typeof ApiJobsIdCompleteRoute
  '/api/jobs/$id/fail': typeof ApiJobsIdFailRoute
  '/api/jobs/$id/heartbeat': typeof ApiJobsIdHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency-health'
    | '/agent-dashboard'
    | '/alerts'
    | '/assign-tasks'
    | '/assistant'
    | '/automation'
    | '/build-agent'
    | '/connected-sites'
    | '/dashboard'
    | '/logs'
    | '/qa-suite'
    | '/settings'
    | '/suggestions'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/resources/prompts'
    | '/resources/sops'
    | '/resources/templates'
    | '/scout-team/$scoutId'
    | '/seo-suite/$toolId'
    | '/sites/$siteId'
    | '/agents/'
    | '/analytics/'
    | '/scout-team/'
    | '/seo-suite/'
    | '/api/analytics/sync'
    | '/api/automation/flows'
    | '/api/events/ingest'
    | '/api/google/ga4'
    | '/api/google/gbp'
    | '/api/google/search-console'
    | '/api/jobs/claim'
    | '/api/tasks/$id'
    | '/api/jobs/'
    | '/api/tasks/'
    | '/api/automation/flows/$id'
    | '/api/jobs/$id/complete'
    | '/api/jobs/$id/fail'
    | '/api/jobs/$id/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency-health'
    | '/agent-dashboard'
    | '/alerts'
    | '/assign-tasks'
    | '/assistant'
    | '/automation'
    | '/build-agent'
    | '/connected-sites'
    | '/dashboard'
    | '/logs'
    | '/qa-suite'
    | '/settings'
    | '/suggestions'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/resources/prompts'
    | '/resources/sops'
    | '/resources/templates'
    | '/scout-team/$scoutId'
    | '/seo-suite/$toolId'
    | '/sites/$siteId'
    | '/agents'
    | '/analytics'
    | '/scout-team'
    | '/seo-suite'
    | '/api/analytics/sync'
    | '/api/automation/flows'
    | '/api/events/ingest'
    | '/api/google/ga4'
    | '/api/google/gbp'
    | '/api/google/search-console'
    | '/api/jobs/claim'
    | '/api/tasks/$id'
    | '/api/jobs'
    | '/api/tasks'
    | '/api/automation/flows/$id'
    | '/api/jobs/$id/complete'
    | '/api/jobs/$id/fail'
    | '/api/jobs/$id/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/agency-health'
    | '/agent-dashboard'
    | '/alerts'
    | '/assign-tasks'
    | '/assistant'
    | '/automation'
    | '/build-agent'
    | '/connected-sites'
    | '/dashboard'
    | '/logs'
    | '/qa-suite'
    | '/settings'
    | '/suggestions'
    | '/agents/$id'
    | '/analytics/business-profile'
    | '/analytics/google-analytics'
    | '/analytics/search-console'
    | '/resources/prompts'
    | '/resources/sops'
    | '/resources/templates'
    | '/scout-team/$scoutId'
    | '/seo-suite/$toolId'
    | '/sites/$siteId'
    | '/agents/'
    | '/analytics/'
    | '/scout-team/'
    | '/seo-suite/'
    | '/api/analytics/sync'
    | '/api/automation/flows'
    | '/api/events/ingest'
    | '/api/google/ga4'
    | '/api/google/gbp'
    | '/api/google/search-console'
    | '/api/jobs/claim'
    | '/api/tasks/$id'
    | '/api/jobs/'
    | '/api/tasks/'
    | '/api/automation/flows/$id'
    | '/api/jobs/$id/complete'
    | '/api/jobs/$id/fail'
    | '/api/jobs/$id/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyHealthRoute: typeof AgencyHealthRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AlertsRoute: typeof AlertsRoute
  AssignTasksRoute: typeof AssignTasksRoute
  AssistantRoute: typeof AssistantRoute
  AutomationRoute: typeof AutomationRoute
  BuildAgentRoute: typeof BuildAgentRoute
  ConnectedSitesRoute: typeof ConnectedSitesRoute
  DashboardRoute: typeof DashboardRoute
  LogsRoute: typeof LogsRoute
  QaSuiteRoute: typeof QaSuiteRoute
  SettingsRoute: typeof SettingsRoute
  SuggestionsRoute: typeof SuggestionsRoute
  AgentsIdRoute: typeof AgentsIdRoute
  AnalyticsBusinessProfileRoute: typeof AnalyticsBusinessProfileRoute
  AnalyticsGoogleAnalyticsRoute: typeof AnalyticsGoogleAnalyticsRoute
  AnalyticsSearchConsoleRoute: typeof AnalyticsSearchConsoleRoute
  ResourcesPromptsRoute: typeof ResourcesPromptsRoute
  ResourcesSopsRoute: typeof ResourcesSopsRoute
  ResourcesTemplatesRoute: typeof ResourcesTemplatesRoute
  ScoutTeamScoutIdRoute: typeof ScoutTeamScoutIdRoute
  SeoSuiteToolIdRoute: typeof SeoSuiteToolIdRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  ScoutTeamIndexRoute: typeof ScoutTeamIndexRoute
  SeoSuiteIndexRoute: typeof SeoSuiteIndexRoute
  ApiAnalyticsSyncRoute: typeof ApiAnalyticsSyncRoute
  ApiAutomationFlowsRoute: typeof ApiAutomationFlowsRouteWithChildren
  ApiEventsIngestRoute: typeof ApiEventsIngestRoute
  ApiGoogleGa4Route: typeof ApiGoogleGa4Route
  ApiGoogleGbpRoute: typeof ApiGoogleGbpRoute
  ApiGoogleSearchConsoleRoute: typeof ApiGoogleSearchConsoleRoute
  ApiJobsClaimRoute: typeof ApiJobsClaimRoute
  ApiTasksIdRoute: typeof ApiTasksIdRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiTasksIndexRoute: typeof ApiTasksIndexRoute
  ApiJobsIdCompleteRoute: typeof ApiJobsIdCompleteRoute
  ApiJobsIdFailRoute: typeof ApiJobsIdFailRoute
  ApiJobsIdHeartbeatRoute: typeof ApiJobsIdHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-health': {
      id: '/agency-health'
      path: '/agency-health'
      fullPath: '/agency-health'
      preLoaderRoute: typeof AgencyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard': {
      id: '/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assign-tasks': {
      id: '/assign-tasks'
      path: '/assign-tasks'
      fullPath: '/assign-tasks'
      preLoaderRoute: typeof AssignTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-agent': {
      id: '/build-agent'
      path: '/build-agent'
      fullPath: '/build-agent'
      preLoaderRoute: typeof BuildAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connected-sites': {
      id: '/connected-sites'
      path: '/connected-sites'
      fullPath: '/connected-sites'
      preLoaderRoute: typeof ConnectedSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-suite': {
      id: '/qa-suite'
      path: '/qa-suite'
      fullPath: '/qa-suite'
      preLoaderRoute: typeof QaSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/business-profile': {
      id: '/analytics/business-profile'
      path: '/analytics/business-profile'
      fullPath: '/analytics/business-profile'
      preLoaderRoute: typeof AnalyticsBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/google-analytics': {
      id: '/analytics/google-analytics'
      path: '/analytics/google-analytics'
      fullPath: '/analytics/google-analytics'
      preLoaderRoute: typeof AnalyticsGoogleAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/search-console': {
      id: '/analytics/search-console'
      path: '/analytics/search-console'
      fullPath: '/analytics/search-console'
      preLoaderRoute: typeof AnalyticsSearchConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/prompts': {
      id: '/resources/prompts'
      path: '/resources/prompts'
      fullPath: '/resources/prompts'
      preLoaderRoute: typeof ResourcesPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/sops': {
      id: '/resources/sops'
      path: '/resources/sops'
      fullPath: '/resources/sops'
      preLoaderRoute: typeof ResourcesSopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/templates': {
      id: '/resources/templates'
      path: '/resources/templates'
      fullPath: '/resources/templates'
      preLoaderRoute: typeof ResourcesTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout-team/': {
      id: '/scout-team/'
      path: '/scout-team'
      fullPath: '/scout-team/'
      preLoaderRoute: typeof ScoutTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout-team/$scoutId': {
      id: '/scout-team/$scoutId'
      path: '/scout-team/$scoutId'
      fullPath: '/scout-team/$scoutId'
      preLoaderRoute: typeof ScoutTeamScoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-suite/': {
      id: '/seo-suite/'
      path: '/seo-suite'
      fullPath: '/seo-suite/'
      preLoaderRoute: typeof SeoSuiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-suite/$toolId': {
      id: '/seo-suite/$toolId'
      path: '/seo-suite/$toolId'
      fullPath: '/seo-suite/$toolId'
      preLoaderRoute: typeof SeoSuiteToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/sync': {
      id: '/api/analytics/sync'
      path: '/api/analytics/sync'
      fullPath: '/api/analytics/sync'
      preLoaderRoute: typeof ApiAnalyticsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automation/flows': {
      id: '/api/automation/flows'
      path: '/api/automation/flows'
      fullPath: '/api/automation/flows'
      preLoaderRoute: typeof ApiAutomationFlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/ingest': {
      id: '/api/events/ingest'
      path: '/api/events/ingest'
      fullPath: '/api/events/ingest'
      preLoaderRoute: typeof ApiEventsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/ga4': {
      id: '/api/google/ga4'
      path: '/api/google/ga4'
      fullPath: '/api/google/ga4'
      preLoaderRoute: typeof ApiGoogleGa4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/gbp': {
      id: '/api/google/gbp'
      path: '/api/google/gbp'
      fullPath: '/api/google/gbp'
      preLoaderRoute: typeof ApiGoogleGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/search-console': {
      id: '/api/google/search-console'
      path: '/api/google/search-console'
      fullPath: '/api/google/search-console'
      preLoaderRoute: typeof ApiGoogleSearchConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/claim': {
      id: '/api/jobs/claim'
      path: '/api/jobs/claim'
      fullPath: '/api/jobs/claim'
      preLoaderRoute: typeof ApiJobsClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/': {
      id: '/api/tasks/'
      path: '/api/tasks'
      fullPath: '/api/tasks/'
      preLoaderRoute: typeof ApiTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/api/tasks/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/automation/flows/$id': {
      id: '/api/automation/flows/$id'
      path: '/$id'
      fullPath: '/api/automation/flows/$id'
      preLoaderRoute: typeof ApiAutomationFlowsIdRouteImport
      parentRoute: typeof ApiAutomationFlowsRoute
    }
    '/api/jobs/$id/complete': {
      id: '/api/jobs/$id/complete'
      path: '/api/jobs/$id/complete'
      fullPath: '/api/jobs/$id/complete'
      preLoaderRoute: typeof ApiJobsIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/fail': {
      id: '/api/jobs/$id/fail'
      path: '/api/jobs/$id/fail'
      fullPath: '/api/jobs/$id/fail'
      preLoaderRoute: typeof ApiJobsIdFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/heartbeat': {
      id: '/api/jobs/$id/heartbeat'
      path: '/api/jobs/$id/heartbeat'
      fullPath: '/api/jobs/$id/heartbeat'
      preLoaderRoute: typeof ApiJobsIdHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAutomationFlowsRouteChildren {
  ApiAutomationFlowsIdRoute: typeof ApiAutomationFlowsIdRoute
}

const ApiAutomationFlowsRouteChildren: ApiAutomationFlowsRouteChildren = {
  ApiAutomationFlowsIdRoute: ApiAutomationFlowsIdRoute,
}

const ApiAutomationFlowsRouteWithChildren =
  ApiAutomationFlowsRoute._addFileChildren(ApiAutomationFlowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyHealthRoute: AgencyHealthRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AlertsRoute: AlertsRoute,
  AssignTasksRoute: AssignTasksRoute,
  AssistantRoute: AssistantRoute,
  AutomationRoute: AutomationRoute,
  BuildAgentRoute: BuildAgentRoute,
  ConnectedSitesRoute: ConnectedSitesRoute,
  DashboardRoute: DashboardRoute,
  LogsRoute: LogsRoute,
  QaSuiteRoute: QaSuiteRoute,
  SettingsRoute: SettingsRoute,
  SuggestionsRoute: SuggestionsRoute,
  AgentsIdRoute: AgentsIdRoute,
  AnalyticsBusinessProfileRoute: AnalyticsBusinessProfileRoute,
  AnalyticsGoogleAnalyticsRoute: AnalyticsGoogleAnalyticsRoute,
  AnalyticsSearchConsoleRoute: AnalyticsSearchConsoleRoute,
  ResourcesPromptsRoute: ResourcesPromptsRoute,
  ResourcesSopsRoute: ResourcesSopsRoute,
  ResourcesTemplatesRoute: ResourcesTemplatesRoute,
  ScoutTeamScoutIdRoute: ScoutTeamScoutIdRoute,
  SeoSuiteToolIdRoute: SeoSuiteToolIdRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  ScoutTeamIndexRoute: ScoutTeamIndexRoute,
  SeoSuiteIndexRoute: SeoSuiteIndexRoute,
  ApiAnalyticsSyncRoute: ApiAnalyticsSyncRoute,
  ApiAutomationFlowsRoute: ApiAutomationFlowsRouteWithChildren,
  ApiEventsIngestRoute: ApiEventsIngestRoute,
  ApiGoogleGa4Route: ApiGoogleGa4Route,
  ApiGoogleGbpRoute: ApiGoogleGbpRoute,
  ApiGoogleSearchConsoleRoute: ApiGoogleSearchConsoleRoute,
  ApiJobsClaimRoute: ApiJobsClaimRoute,
  ApiTasksIdRoute: ApiTasksIdRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiTasksIndexRoute: ApiTasksIndexRoute,
  ApiJobsIdCompleteRoute: ApiJobsIdCompleteRoute,
  ApiJobsIdFailRoute: ApiJobsIdFailRoute,
  ApiJobsIdHeartbeatRoute: ApiJobsIdHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
